default:
  image: arm32v7/maven

build-job:
  stage: build
  script:
    - echo "Compiling, $GITLAB_USER_LOGIN!"
    - mvn compile

test-job: 
  stage: test
  script:
    - echo "Testing, $GITLAB_USER_LOGIN!"
    - mvn test


